exports.data = {
  users: [
    {
      firstName: "Carina",
      lastName: "Dziwisz",
      email: "c.dziwisz@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Leonid",
      lastName: "Livock",
      email: "l.livock@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Esdras",
      lastName: "Lingard",
      email: "e.lingard@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Norrie",
      lastName: "Letteresse",
      email: "n.letteresse@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Lionel",
      lastName: "Eirwin",
      email: "l.eirwin@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Reiko",
      lastName: "Grevatt",
      email: "r.grevatt@example.com",
      password: "P@ssw0rd",
      role: "instructor",
    },
    {
      firstName: "Dena",
      lastName: "Stooders",
      email: "d.stooders@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Garvin",
      lastName: "Stockings",
      email: "g.stockings@example.com",
      password: "P@ssw0rd",
      role: "assistant",
    },
    {
      firstName: "Carolee",
      lastName: "ducarme",
      email: "c.ducarme@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Neddie",
      lastName: "Farrin",
      email: "n.farrin@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Corey",
      lastName: "Bricham",
      email: "c.bricham@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Nelie",
      lastName: "Durtnel",
      email: "n.durtnel@example.com",
      password: "P@ssw0rd",
      role: "instructor",
    },
    {
      firstName: "Dyan",
      lastName: "Eplett",
      email: "d.eplett@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Chantal",
      lastName: "Guerola",
      email: "c.guerola@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ignatius",
      lastName: "Cohr",
      email: "i.cohr@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Cyrus",
      lastName: "Redhills",
      email: "c.redhills@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Carolin",
      lastName: "Drewett",
      email: "c.drewett@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Daria",
      lastName: "Dawidsohn",
      email: "d.dawidsohn@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Nickolai",
      lastName: "McSparran",
      email: "n.mcsparran@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Boot",
      lastName: "Dossit",
      email: "b.dossit@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Aurora",
      lastName: "Bydaway",
      email: "a.bydaway@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Jenda",
      lastName: "Barnardo",
      email: "j.barnardo@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Rusty",
      lastName: "Jereatt",
      email: "r.jereatt@example.com",
      password: "P@ssw0rd",
      role: "assistant",
    },
    {
      firstName: "Devina",
      lastName: "Bogies",
      email: "d.bogies@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ninon",
      lastName: "Cardinale",
      email: "n.cardinale@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Benjie",
      lastName: "Whibley",
      email: "b.whibley@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Jerad",
      lastName: "Souley",
      email: "j.souley@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ardith",
      lastName: "Klimowski",
      email: "a.klimowski@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Claybourne",
      lastName: "Cade",
      email: "c.cade@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Nikolas",
      lastName: "Rockwell",
      email: "n.rockwell@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Terrence",
      lastName: "Gerok",
      email: "t.gerok@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Willow",
      lastName: "Earley",
      email: "w.earley@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Othelia",
      lastName: "Hanrahan",
      email: "o.hanrahan@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Leontine",
      lastName: "Gregor",
      email: "l.gregor@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Erie",
      lastName: "Elston",
      email: "e.elston@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Gloria",
      lastName: "Collin",
      email: "g.collin@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Gisela",
      lastName: "Alderton",
      email: "g.alderton@example.com",
      password: "P@ssw0rd",
      role: "instructor",
    },
    {
      firstName: "Etty",
      lastName: "Conisbee",
      email: "e.conisbee@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Francesco",
      lastName: "Simenel",
      email: "f.simenel@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ransom",
      lastName: "Forstall",
      email: "r.forstall@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ceil",
      lastName: "Stoop",
      email: "c.stoop@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Fredi",
      lastName: "Platts",
      email: "f.platts@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Dee",
      lastName: "McTiernan",
      email: "d.mctiernan@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Klara",
      lastName: "Shoppee",
      email: "k.shoppee@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Fabiano",
      lastName: "Tomalin",
      email: "f.tomalin@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Nikola",
      lastName: "Deme",
      email: "n.deme@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Karlens",
      lastName: "Brooke",
      email: "k.brooke@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Mady",
      lastName: "Thewys",
      email: "m.thewys@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Cari",
      lastName: "Lawford",
      email: "c.lawford@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Emelda",
      lastName: "Gurg",
      email: "e.gurg@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Buckie",
      lastName: "Zylbermann",
      email: "b.zylbermann@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Hinze",
      lastName: "Knok",
      email: "h.knok@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Tessi",
      lastName: "Barefoot",
      email: "t.barefoot@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Baillie",
      lastName: "Cromwell",
      email: "b.cromwell@example.com",
      password: "P@ssw0rd",
      role: "instructor",
    },
    {
      firstName: "Ula",
      lastName: "Arlet",
      email: "u.arlet@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Kellyann",
      lastName: "Tollerfield",
      email: "k.tollerfield@example.com",
      password: "P@ssw0rd",
      role: "instructor",
    },
    {
      firstName: "Cinda",
      lastName: "Stollberger",
      email: "c.stollberger@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Elden",
      lastName: "Gillibrand",
      email: "e.gillibrand@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Rasia",
      lastName: "Burleton",
      email: "r.burleton@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Baxter",
      lastName: "Berzen",
      email: "b.berzen@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Erroll",
      lastName: "Ponte",
      email: "e.ponte@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Sher",
      lastName: "Chrstine",
      email: "s.chrstine@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Francklyn",
      lastName: "Wiltshaw",
      email: "f.wiltshaw@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Mellisent",
      lastName: "Ygoe",
      email: "m.ygoe@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Melissa",
      lastName: "De Gregoli",
      email: "m.de gregoli@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Bowie",
      lastName: "Sycamore",
      email: "b.sycamore@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Isa",
      lastName: "Rugieri",
      email: "i.rugieri@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Roberta",
      lastName: "Dall",
      email: "r.dall@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Dwayne",
      lastName: "Backman",
      email: "d.backman@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ina",
      lastName: "Dwire",
      email: "i.dwire@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Tarah",
      lastName: "Cunnah",
      email: "t.cunnah@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Noel",
      lastName: "Middell",
      email: "n.middell@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Nikki",
      lastName: "Chastey",
      email: "n.chastey@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Edmon",
      lastName: "St. Queintain",
      email: "e.st. queintain@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Nat",
      lastName: "Drains",
      email: "n.drains@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ivan",
      lastName: "Ansill",
      email: "i.ansill@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Lurlene",
      lastName: "Tofpik",
      email: "l.tofpik@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Gabi",
      lastName: "Kenworthy",
      email: "g.kenworthy@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Cesare",
      lastName: "McCloud",
      email: "c.mccloud@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Rriocard",
      lastName: "Stemson",
      email: "r.stemson@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Garth",
      lastName: "Chaise",
      email: "g.chaise@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Deanna",
      lastName: "Easterbrook",
      email: "d.easterbrook@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Livvy",
      lastName: "Jelf",
      email: "l.jelf@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Maible",
      lastName: "Hansmann",
      email: "m.hansmann@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Elladine",
      lastName: "Posner",
      email: "e.posner@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ky",
      lastName: "Riolfi",
      email: "k.riolfi@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Alyson",
      lastName: "Shitliffe",
      email: "a.shitliffe@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Inigo",
      lastName: "Ahrendsen",
      email: "i.ahrendsen@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Greg",
      lastName: "Sapson",
      email: "g.sapson@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Maybelle",
      lastName: "Mewe",
      email: "m.mewe@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Vasily",
      lastName: "Merioth",
      email: "v.merioth@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Henrietta",
      lastName: "Tait",
      email: "h.tait@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Brynn",
      lastName: "Slatter",
      email: "b.slatter@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Fair",
      lastName: "Gason",
      email: "f.gason@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Raychel",
      lastName: "Caulwell",
      email: "r.caulwell@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Amandie",
      lastName: "Ancliff",
      email: "a.ancliff@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Zelig",
      lastName: "Gettins",
      email: "z.gettins@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Lilia",
      lastName: "Stansell",
      email: "l.stansell@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Joline",
      lastName: "Slatcher",
      email: "j.slatcher@example.com",
      password: "P@ssw0rd",
      role: "instructor",
    },
    {
      firstName: "Antonie",
      lastName: "Bigrigg",
      email: "a.bigrigg@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
  ],
  courses: [
    { title: "MATH101", description: "Introduction to Mathematics" },
    { title: "MATH102", description: "Intermediate Mathematics" },
    { title: "MATH201", description: "Advanced Mathematics" },
    { title: "MATH301", description: "Calculus and Analytical Geometry" },
    { title: "ENGL101", description: "English Composition" },
    { title: "ENGL102", description: "Introduction to Literature" },
    { title: "ENGL201", description: "American Literature" },
    { title: "ENGL202", description: "British Literature" },
    { title: "HIST301", description: "World History" },
    { title: "HIST302", description: "European History" },
    { title: "HIST303", description: "American History" },
    { title: "HIST305", description: "Ancient Civilizations" },
    { title: "PHYS101", description: "Physics Fundamentals" },
    { title: "PHYS201", description: "Classical Mechanics" },
    { title: "CHEM101", description: "General Chemistry" },
    { title: "CHEM201", description: "Organic Chemistry" },
  ],
};
