exports.data = {
  users: [
    {
      firstName: "Carina",
      lastName: "Dziwisz",
      email: "C.Dziwisz@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Leonid",
      lastName: "Livock",
      email: "L.Livock@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Esdras",
      lastName: "Lingard",
      email: "E.Lingard@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Norrie",
      lastName: "Letteresse",
      email: "N.Letteresse@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Lionel",
      lastName: "Eirwin",
      email: "L.Eirwin@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Reiko",
      lastName: "Grevatt",
      email: "R.Grevatt@example.com",
      password: "P@ssw0rd",
      role: "instructor",
    },
    {
      firstName: "Dena",
      lastName: "Stooders",
      email: "D.Stooders@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Garvin",
      lastName: "Stockings",
      email: "G.Stockings@example.com",
      password: "P@ssw0rd",
      role: "assistant",
    },
    {
      firstName: "Carolee",
      lastName: "ducarme",
      email: "C.ducarme@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Neddie",
      lastName: "Farrin",
      email: "N.Farrin@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Corey",
      lastName: "Bricham",
      email: "C.Bricham@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Nelie",
      lastName: "Durtnel",
      email: "N.Durtnel@example.com",
      password: "P@ssw0rd",
      role: "instructor",
    },
    {
      firstName: "Dyan",
      lastName: "Eplett",
      email: "D.Eplett@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Chantal",
      lastName: "Guerola",
      email: "C.Guerola@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ignatius",
      lastName: "Cohr",
      email: "I.Cohr@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Cyrus",
      lastName: "Redhills",
      email: "C.Redhills@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Carolin",
      lastName: "Drewett",
      email: "C.Drewett@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Daria",
      lastName: "Dawidsohn",
      email: "D.Dawidsohn@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Nickolai",
      lastName: "McSparran",
      email: "N.McSparran@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Boot",
      lastName: "Dossit",
      email: "B.Dossit@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Aurora",
      lastName: "Bydaway",
      email: "A.Bydaway@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Jenda",
      lastName: "Barnardo",
      email: "J.Barnardo@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Rusty",
      lastName: "Jereatt",
      email: "R.Jereatt@example.com",
      password: "P@ssw0rd",
      role: "assistant",
    },
    {
      firstName: "Devina",
      lastName: "Bogies",
      email: "D.Bogies@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ninon",
      lastName: "Cardinale",
      email: "N.Cardinale@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Benjie",
      lastName: "Whibley",
      email: "B.Whibley@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Jerad",
      lastName: "Souley",
      email: "J.Souley@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ardith",
      lastName: "Klimowski",
      email: "A.Klimowski@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Claybourne",
      lastName: "Cade",
      email: "C.Cade@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Nikolas",
      lastName: "Rockwell",
      email: "N.Rockwell@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Terrence",
      lastName: "Gerok",
      email: "T.Gerok@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Willow",
      lastName: "Earley",
      email: "W.Earley@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Othelia",
      lastName: "Hanrahan",
      email: "O.Hanrahan@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Leontine",
      lastName: "Gregor",
      email: "L.Gregor@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Erie",
      lastName: "Elston",
      email: "E.Elston@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Gloria",
      lastName: "Collin",
      email: "G.Collin@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Gisela",
      lastName: "Alderton",
      email: "G.Alderton@example.com",
      password: "P@ssw0rd",
      role: "instructor",
    },
    {
      firstName: "Etty",
      lastName: "Conisbee",
      email: "E.Conisbee@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Francesco",
      lastName: "Simenel",
      email: "F.Simenel@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ransom",
      lastName: "Forstall",
      email: "R.Forstall@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ceil",
      lastName: "Stoop",
      email: "C.Stoop@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Fredi",
      lastName: "Platts",
      email: "F.Platts@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Dee",
      lastName: "McTiernan",
      email: "D.McTiernan@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Klara",
      lastName: "Shoppee",
      email: "K.Shoppee@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Fabiano",
      lastName: "Tomalin",
      email: "F.Tomalin@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Nikola",
      lastName: "Deme",
      email: "N.Deme@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Karlens",
      lastName: "Brooke",
      email: "K.Brooke@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Mady",
      lastName: "Thewys",
      email: "M.Thewys@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Cari",
      lastName: "Lawford",
      email: "C.Lawford@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Emelda",
      lastName: "Gurg",
      email: "E.Gurg@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Buckie",
      lastName: "Zylbermann",
      email: "B.Zylbermann@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Hinze",
      lastName: "Knok",
      email: "H.Knok@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Tessi",
      lastName: "Barefoot",
      email: "T.Barefoot@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Baillie",
      lastName: "Cromwell",
      email: "B.Cromwell@example.com",
      password: "P@ssw0rd",
      role: "instructor",
    },
    {
      firstName: "Ula",
      lastName: "Arlet",
      email: "U.Arlet@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Kellyann",
      lastName: "Tollerfield",
      email: "K.Tollerfield@example.com",
      password: "P@ssw0rd",
      role: "instructor",
    },
    {
      firstName: "Cinda",
      lastName: "Stollberger",
      email: "C.Stollberger@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Elden",
      lastName: "Gillibrand",
      email: "E.Gillibrand@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Rasia",
      lastName: "Burleton",
      email: "R.Burleton@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Baxter",
      lastName: "Berzen",
      email: "B.Berzen@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Erroll",
      lastName: "Ponte",
      email: "E.Ponte@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Sher",
      lastName: "Chrstine",
      email: "S.Chrstine@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Francklyn",
      lastName: "Wiltshaw",
      email: "F.Wiltshaw@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Mellisent",
      lastName: "Ygoe",
      email: "M.Ygoe@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Melissa",
      lastName: "De Gregoli",
      email: "M.De Gregoli@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Bowie",
      lastName: "Sycamore",
      email: "B.Sycamore@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Isa",
      lastName: "Rugieri",
      email: "I.Rugieri@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Roberta",
      lastName: "Dall",
      email: "R.Dall@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Dwayne",
      lastName: "Backman",
      email: "D.Backman@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ina",
      lastName: "Dwire",
      email: "I.Dwire@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Tarah",
      lastName: "Cunnah",
      email: "T.Cunnah@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Noel",
      lastName: "Middell",
      email: "N.Middell@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Nikki",
      lastName: "Chastey",
      email: "N.Chastey@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Edmon",
      lastName: "St. Queintain",
      email: "E.St. Queintain@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Nat",
      lastName: "Drains",
      email: "N.Drains@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ivan",
      lastName: "Ansill",
      email: "I.Ansill@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Lurlene",
      lastName: "Tofpik",
      email: "L.Tofpik@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Gabi",
      lastName: "Kenworthy",
      email: "G.Kenworthy@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Cesare",
      lastName: "McCloud",
      email: "C.McCloud@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Rriocard",
      lastName: "Stemson",
      email: "R.Stemson@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Garth",
      lastName: "Chaise",
      email: "G.Chaise@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Deanna",
      lastName: "Easterbrook",
      email: "D.Easterbrook@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Livvy",
      lastName: "Jelf",
      email: "L.Jelf@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Maible",
      lastName: "Hansmann",
      email: "M.Hansmann@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Elladine",
      lastName: "Posner",
      email: "E.Posner@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Ky",
      lastName: "Riolfi",
      email: "K.Riolfi@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Alyson",
      lastName: "Shitliffe",
      email: "A.Shitliffe@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Inigo",
      lastName: "Ahrendsen",
      email: "I.Ahrendsen@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Greg",
      lastName: "Sapson",
      email: "G.Sapson@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Maybelle",
      lastName: "Mewe",
      email: "M.Mewe@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Vasily",
      lastName: "Merioth",
      email: "V.Merioth@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Henrietta",
      lastName: "Tait",
      email: "H.Tait@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Brynn",
      lastName: "Slatter",
      email: "B.Slatter@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Fair",
      lastName: "Gason",
      email: "F.Gason@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Raychel",
      lastName: "Caulwell",
      email: "R.Caulwell@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Amandie",
      lastName: "Ancliff",
      email: "A.Ancliff@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Zelig",
      lastName: "Gettins",
      email: "Z.Gettins@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Lilia",
      lastName: "Stansell",
      email: "L.Stansell@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
    {
      firstName: "Joline",
      lastName: "Slatcher",
      email: "J.Slatcher@example.com",
      password: "P@ssw0rd",
      role: "instructor",
    },
    {
      firstName: "Antonie",
      lastName: "Bigrigg",
      email: "A.Bigrigg@example.com",
      password: "P@ssw0rd",
      role: "student",
    },
  ],
  courses: [
    { title: "MATH101", description: "Introduction to Mathematics" },
    { title: "MATH102", description: "Intermediate Mathematics" },
    { title: "MATH201", description: "Advanced Mathematics" },
    { title: "MATH301", description: "Calculus and Analytical Geometry" },
    { title: "ENGL101", description: "English Composition" },
    { title: "ENGL102", description: "Introduction to Literature" },
    { title: "ENGL201", description: "American Literature" },
    { title: "ENGL202", description: "British Literature" },
    { title: "HIST301", description: "World History" },
    { title: "HIST302", description: "European History" },
    { title: "HIST303", description: "American History" },
    { title: "HIST305", description: "Ancient Civilizations" },
    { title: "PHYS101", description: "Physics Fundamentals" },
    { title: "PHYS201", description: "Classical Mechanics" },
    { title: "CHEM101", description: "General Chemistry" },
    { title: "CHEM201", description: "Organic Chemistry" },
  ],
};
